#!/usr/bin/env python3

from argparse import ArgumentParser
import subprocess

vers = "0.0.1"

parser = ArgumentParser()

build_run = parser.add_mutually_exclusive_group()
build_run.add_argument("--build", "-b", action="store_true")
build_run.add_argument("--run", "-r", action="store_true")

parser.add_argument("kwargs", nargs="*", desription="Args to pass to the"
                    "Docker/ucfai-admin module")

args = parser.parse_args()


if args.build:
    subprocess.call(
        f"docker build -f Dockerfile -t ucfai/admin:{vers} {arg.kwargs} .",
        shell=True
    )
elif args.run:
    assert args.kwargs
    subprocess.call(
        f"docker run ucfai/admin:{vers} {arg.kwargs}",
        shell=True
    )